services:
  smb-proxy:
    build: .
    container_name: smb-proxy
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    ports:
      - "1445:445"
    env_file:
      - .env
    environment:
      SMB_PROXY_MODE: gateway
      LOCAL_ALLOW_GUEST: "false"
